name: zPermissions
version: ${version}
main: org.tyrannyofheaven.bukkit.zPermissions.ZPermissionsPlugin
description: Superperms implementation with Bukkit database backend
author: ZerothAngel
database: false
load: STARTUP

commands:
  permissions:
    description: Top-level command for zPermissions
    aliases: [perm, perms, zpermissions, zperm, zperms]
  promote:
    description: Promote a player up a rank
    aliases: [rankup, zpromote]
  demote:
    description: Demote a player down a rank
    aliases: [rankdown, zdemote]
  setrank:
    description: Set the rank of a player
    aliases: zsetrank
  unsetrank:
    description: Remove a player from a track
    aliases: zunsetrank

permissions:
  zpermissions.*:
    description: All-inclusive permission for zPermissions
    default: op
    children:
      zpermissions.player.*: true
      zpermissions.group.*: true
      zpermissions.list: true
      zpermissions.check: true
      zpermissions.check.other: true
      zpermissions.inspect: true
      zpermissions.inspect.other: true
      zpermissions.diff: true
      zpermissions.search: true
      zpermissions.mygroups: true
      zpermissions.mychat: true
      zpermissions.reload: true
      zpermissions.refresh: true
      zpermissions.export: true
      zpermissions.import: true
      zpermissions.purge: true
      zpermissions.cleanup: true
      zpermissions.rank: true
      zpermissions.rank.*: true
      zpermissions.uuid-cache: true
  zpermissions.rank:
    description: Allows use of all rank-related commands
    children:
      zpermissions.promote: true
      zpermissions.demote: true
      zpermissions.setrank: true
      zpermissions.unsetrank: true
  zpermissions.rank.*:
    description: Allows use of rank commands on all tracks
    children:
      zpermissions.promote.*: true
      zpermissions.demote.*: true
      zpermissions.setrank.*: true
      zpermissions.unsetrank.*: true
  zpermissions.player:
    description: Allows use of the /permissions player command
    children:
      zpermissions.player.*: true
  zpermissions.player.*:
    description: Allows use of the /permissions player command
    children:
      zpermissions.player.manage: true
  zpermissions.player.manage:
    children:
      zpermissions.player.view: true
      zpermissions.player.chat: true
  zpermissions.group:
    description: Allows use of the /permissions group command
    children:
      zpermissions.group.*: true
  zpermissions.group.*:
    description: Allows use of the /permissions group command
    children:
      zpermissions.group.manage: true
  zpermissions.group.manage:
    children:
      zpermissions.group.view: true
      zpermissions.group.chat: true
  zpermissions.list:
    description: Allows use of the /permissions list command
  zpermissions.check:
    description: Allows use of the /permissions check command
  zpermissions.check.other:
    description: Allows use of the /permissions check command on others
  zpermissions.inspect:
    description: Allows use of the /permissions inspect command
  zpermissions.inspect.other:
    description: Allows use of the /permissions inspect command on others
  zpermissions.diff:
    description: Allows use of the /permissions diff command
  zpermissions.search:
    description: Allows use of the /permissions search command
  zpermissions.mygroups:
    description: Allows use of the /permissions mygroups command
  zpermissions.mychat:
    description: Allows use of the /permissions prefix and /permissions suffix commands
  zpermissions.reload:
    description: Allows use of the /permissions reload command
  zpermissions.refresh:
    description: Allows use of the /permissions refresh command
  zpermissions.export:
    description: Allows use of the /permissions export command
  zpermissions.import:
    description: Allows use of the /permissions import command
  zpermissions.purge:
    description: Allows use of the /permissions purge command
  zpermissions.cleanup:
    description: Allows use of the /permissions cleanup command
  zpermissions.promote:
    description: Allows use of the /promote command
  zpermissions.promote.*:
    description: Allows use of /promote on all tracks
  zpermissions.demote:
    description: Allows use of the /demote command
  zpermissions.demote.*:
    description: Allows use of /demote on all tracks
  zpermissions.setrank:
    description: Allows use of the /setrank command
  zpermissions.setrank.*:
    description: Allows use of /setrank on all tracks
  zpermissions.unsetrank:
    description: Allows use of the /unsetrank command
  zpermissions.unsetrank.*:
    description: Allows use of /unsetrank on all tracks
  zpermissions.notify.*:
    description: Receives all notifications
    default: false
    children:
      zpermissions.notify.rank: true
      zpermissions.notify.expiration: true
  zpermissions.notify.rank:
    description: Receives rank command notitifications
    default: false
    children:
      zpermissions.notify.promote: true
      zpermissions.notify.demote: true
      zpermissions.notify.setrank: true
      zpermissions.notify.unsetrank: true
  zpermissions.notify.promote:
    description: Receives /promote notifications
    default: false
  zpermissions.notify.demote:
    description: Receives /demote notifications
    default: false
  zpermissions.notify.setrank:
    description: Receives /setrank notifications
    default: false
  zpermissions.notify.unsetrank:
    description: Receives /unsetrank notifications
    default: false
  zpermissions.notify.expiration:
    description: Receives temporary membership expiration notifications
    default: false
  zpermissions.notify.self.*:
    description: Receives all notifications for self
    default: false
    children:
      zpermissions.notify.self.expiration: true
  zpermissions.notify.self.expiration:
    description: Receives temporary membership expiration notifications for self
    default: false
  zpermissions.error.detail:
    description: Receives full details about missing permissions
    default: true
  zpermissions.uuid-cache:
    description: Allows use of /permissions uuid-cache commands
